### PR TITLE
chore: include PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #31: chore: Include PULL_REQUEST_TEMPLATE.md
**Description**

I'll think it will be very beneficial to include a `PULL_REQUEST_TEMPLATE.md` similar to [this](https://github.com/felangel/bloc/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

### PR DESCRIPTION
**Pull request by alestiago**
# Description

Includes a `PULL_REQUEST_TEMPLATE.md`.

## Checklist

- [X] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [X] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [X] I have updated/added tests for ALL new/updated/fixed functionality.
- [X] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [X] I have updated/added relevant examples in `examples`.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change. (Indicate it in the [Conventional Commit] prefix with a `!`,
  e.g. `feat!:`, `fix!:`).
- [X] No, this is *not* a breaking change.

## Related Issues

Aims to resolve #31

### CODE REVIEW

**Comment by spydon** [comment]
I agree that we should have a PR template, but I don't think we should introduce a new one, but try to be consistent in the organization and use the one we currently have in Flame.

**Comment by alestiago** [comment]
> I agree that we should have a PR template, but I don't think we should introduce a new one, but try to be consistent in the organization and use the one we currently have in Flame.

@spydon true, of course! I'm so used to seeing the template BloC uses that I didn't contemplate the Flame team had its own one 😅. I've used Flame's template instead now.

**Review by spydon — APPROVED** [review]
Lgtm!

**Comment by spydon** [comment]
> @spydon should we modify it to exclude "I have read the [Contributor Guide] and followed the process outlined for submitting PRs." from the checklist? Since there is none currently under this repo.
> 
> I also think the section: "Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process."
> 
> Should be commented out. As the [above](https://github.com/flame-engine/forge2d/pull/32#issue-1154599250).

Sounds good, that PR should first be made to Flame also then.

**Comment by alestiago** [comment]
I'll raise the PR to Flame to regarding commenting out that section.

On the other, hand I think the Contributor Guide checklist option makes sense since there is one on the Flame repo but not one in this repo.

**Comment by alestiago** [comment]
This PR is currently blocked.

Waiting for this [issue](https://github.com/flame-engine/flame/issues/1411) to be resolved first.

**Review by spydon — APPROVED** [review]

**Pull request merged**
